---
sudo: required
language: c
cache:
  - pip
  - directories:
    - lib
    - include
before_install:
  - pip install --user cpp-coveralls
install:
  - sudo apt-get update
  - sudo apt-get install musl-tools
  - ./build_static_sqlite.sh
script:
  # TODO: update this to link against libmusl
  - make CC=gcc test
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
