---
sudo: required
language: c
cache:
  - directories:
    - lib
    - include
before_install:
  - pip install --user cpp-coveralls
install:
  - sudo apt-get update
  - sudo apt-get install musl-tools libdbd-sqlite3-perl libsqlite3-dev
  - ./build_static_sqlite.sh
script:
  - cp travis-local.mk local.mk
  # TODO: update this to link against libmusl
  - make test
after_success:
  - coveralls --gcov-options '\-lp' $(for d in * */t; do printf " -i $d"; done)
