# booker-add-product: adds a product to the database

APP = add-product

SRC = main.c

include ../config.mk
include ../default.mk

CPPFLAGS += -I../include
LDFLAGS += -L../lib -lsqlite3 -lpthread -ldl
